//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


    

namespace FaultContracts
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RequiredClaimsNotPresentException : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] ClaimsNotPresentField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ClaimsNotPresent
        {
            get
            {
                return this.ClaimsNotPresentField;
            }
            set
            {
                this.ClaimsNotPresentField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyAlertsService")]
public interface IMyAlertsService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAlertsService/GetMyAlerts", ReplyAction="http://tempuri.org/IMyAlertsService/GetMyAlertsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(FaultContracts.RequiredClaimsNotPresentException), Action="http://tempuri.org/IMyAlertsService/GetMyAlertsRequiredClaimsNotPresentExceptionF" +
        "ault", Name="RequiredClaimsNotPresentException", Namespace="http://schemas.datacontract.org/2004/07/FaultContracts")]
    DataContracts.Alert[] GetMyAlerts();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMyAlertsServiceChannel : IMyAlertsService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MyAlertsServiceClient : System.ServiceModel.ClientBase<IMyAlertsService>, IMyAlertsService
{
    
    public MyAlertsServiceClient()
    {
    }
    
    public MyAlertsServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyAlertsServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyAlertsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyAlertsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DataContracts.Alert[] GetMyAlerts()
    {
        return base.Channel.GetMyAlerts();
    }
}
