//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.112
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.Serialization;


namespace Rss
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RssFeed : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Rss.RssChannel[] ChannelsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssChannel[] Channels
        {
            get
            {
                return this.ChannelsField;
            }
            set
            {
                this.ChannelsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RssChannel : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Rss.RssCategory[] CategoriesField;
        
        private Rss.RssCloud CloudField;
        
        private string CopyrightField;
        
        private string DescriptionField;
        
        private string DocsField;
        
        private string ExplicitChannelField;
        
        private string GeneratorField;
        
        private Rss.RssImage ImageField;
        
        private Rss.RssCategory[] ItemCategoriesField;
        
        private Rss.RssItem[] ItemRecommendationsField;
        
        private Rss.RssItem[] ItemsField;
        
        private string LanguageField;
        
        private string LastBuildDateField;
        
        private string LastWriteTimeField;
        
        private string LinkField;
        
        private string ManagingEditorField;
        
        private string PathField;
        
        private string PubDateField;
        
        private string RatingField;
        
        private string SkipDaysField;
        
        private string SkipHoursField;
        
        private string SummaryField;
        
        private string TextInputField;
        
        private string TimeToLiveField;
        
        private string TitleField;
        
        private string WebmasterField;
        
        private string XmlUrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssCategory[] Categories
        {
            get
            {
                return this.CategoriesField;
            }
            set
            {
                this.CategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssCloud Cloud
        {
            get
            {
                return this.CloudField;
            }
            set
            {
                this.CloudField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Copyright
        {
            get
            {
                return this.CopyrightField;
            }
            set
            {
                this.CopyrightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Docs
        {
            get
            {
                return this.DocsField;
            }
            set
            {
                this.DocsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExplicitChannel
        {
            get
            {
                return this.ExplicitChannelField;
            }
            set
            {
                this.ExplicitChannelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Generator
        {
            get
            {
                return this.GeneratorField;
            }
            set
            {
                this.GeneratorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssImage Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssCategory[] ItemCategories
        {
            get
            {
                return this.ItemCategoriesField;
            }
            set
            {
                this.ItemCategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssItem[] ItemRecommendations
        {
            get
            {
                return this.ItemRecommendationsField;
            }
            set
            {
                this.ItemRecommendationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssItem[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastBuildDate
        {
            get
            {
                return this.LastBuildDateField;
            }
            set
            {
                this.LastBuildDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastWriteTime
        {
            get
            {
                return this.LastWriteTimeField;
            }
            set
            {
                this.LastWriteTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this.LinkField;
            }
            set
            {
                this.LinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagingEditor
        {
            get
            {
                return this.ManagingEditorField;
            }
            set
            {
                this.ManagingEditorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PubDate
        {
            get
            {
                return this.PubDateField;
            }
            set
            {
                this.PubDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkipDays
        {
            get
            {
                return this.SkipDaysField;
            }
            set
            {
                this.SkipDaysField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkipHours
        {
            get
            {
                return this.SkipHoursField;
            }
            set
            {
                this.SkipHoursField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Summary
        {
            get
            {
                return this.SummaryField;
            }
            set
            {
                this.SummaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TextInput
        {
            get
            {
                return this.TextInputField;
            }
            set
            {
                this.TextInputField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeToLive
        {
            get
            {
                return this.TimeToLiveField;
            }
            set
            {
                this.TimeToLiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Webmaster
        {
            get
            {
                return this.WebmasterField;
            }
            set
            {
                this.WebmasterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlUrl
        {
            get
            {
                return this.XmlUrlField;
            }
            set
            {
                this.XmlUrlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RssCloud : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DomainField;
        
        private string PathField;
        
        private string PortField;
        
        private string ProtocolField;
        
        private string RegisterProcedureField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Port
        {
            get
            {
                return this.PortField;
            }
            set
            {
                this.PortField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Protocol
        {
            get
            {
                return this.ProtocolField;
            }
            set
            {
                this.ProtocolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterProcedure
        {
            get
            {
                return this.RegisterProcedureField;
            }
            set
            {
                this.RegisterProcedureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RssImage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string HeightField;
        
        private string ImageTargetField;
        
        private string LinkField;
        
        private string TitleField;
        
        private string UrlField;
        
        private string WidthField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ImageTarget
        {
            get
            {
                return this.ImageTargetField;
            }
            set
            {
                this.ImageTargetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this.LinkField;
            }
            set
            {
                this.LinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Width
        {
            get
            {
                return this.WidthField;
            }
            set
            {
                this.WidthField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RssCategory : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CategoryField;
        
        private string CategoryDomainField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryDomain
        {
            get
            {
                return this.CategoryDomainField;
            }
            set
            {
                this.CategoryDomainField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RssItem : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthorField;
        
        private Rss.RssCategory[] CategoriesField;
        
        private string CommentsField;
        
        private string DescriptionField;
        
        private string DurationField;
        
        private Rss.RssEnclosure[] EnclosuresField;
        
        private string GuidField;
        
        private Rss.RssImage ImageField;
        
        private string LinkField;
        
        private string PubDateField;
        
        private string RatingField;
        
        private string SourceField;
        
        private string SubtitleField;
        
        private string TitleField;
        
        private string XmlUrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssCategory[] Categories
        {
            get
            {
                return this.CategoriesField;
            }
            set
            {
                this.CategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments
        {
            get
            {
                return this.CommentsField;
            }
            set
            {
                this.CommentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duration
        {
            get
            {
                return this.DurationField;
            }
            set
            {
                this.DurationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssEnclosure[] Enclosures
        {
            get
            {
                return this.EnclosuresField;
            }
            set
            {
                this.EnclosuresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Guid
        {
            get
            {
                return this.GuidField;
            }
            set
            {
                this.GuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Rss.RssImage Image
        {
            get
            {
                return this.ImageField;
            }
            set
            {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Link
        {
            get
            {
                return this.LinkField;
            }
            set
            {
                this.LinkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PubDate
        {
            get
            {
                return this.PubDateField;
            }
            set
            {
                this.PubDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subtitle
        {
            get
            {
                return this.SubtitleField;
            }
            set
            {
                this.SubtitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlUrl
        {
            get
            {
                return this.XmlUrlField;
            }
            set
            {
                this.XmlUrlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RssEnclosure : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool DownloadField;
        
        private string LengthField;
        
        private string MediaCategoryField;
        
        private string MediaPlayerHtmlForEnclosureField;
        
        private string TypeField;
        
        private string UrlField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Download
        {
            get
            {
                return this.DownloadField;
            }
            set
            {
                this.DownloadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MediaCategory
        {
            get
            {
                return this.MediaCategoryField;
            }
            set
            {
                this.MediaCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MediaPlayerHtmlForEnclosure
        {
            get
            {
                return this.MediaPlayerHtmlForEnclosureField;
            }
            set
            {
                this.MediaPlayerHtmlForEnclosureField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url
        {
            get
            {
                return this.UrlField;
            }
            set
            {
                this.UrlField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IRSSService")]
public interface IRSSService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRSSService/GetFeed", ReplyAction="http://tempuri.org/IRSSService/GetFeedResponse")]
    Rss.RssFeed GetFeed();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IRSSServiceChannel : IRSSService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class RSSServiceClient : System.ServiceModel.ClientBase<IRSSService>, IRSSService
{
    
    public RSSServiceClient()
    {
    }
    
    public RSSServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public RSSServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RSSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public RSSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Rss.RssFeed GetFeed()
    {
        return base.Channel.GetFeed();
    }
}
