//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.112
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyAlertsService")]
public interface IMyAlertsService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyAlertsService/GetMyAlerts", ReplyAction="http://tempuri.org/IMyAlertsService/GetMyAlertsResponse")]
    DataContracts.Alert[] GetMyAlerts();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IMyAlertsServiceChannel : IMyAlertsService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class MyAlertsServiceClient : System.ServiceModel.ClientBase<IMyAlertsService>, IMyAlertsService
{
    
    public MyAlertsServiceClient()
    {
    }
    
    public MyAlertsServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyAlertsServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyAlertsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyAlertsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public DataContracts.Alert[] GetMyAlerts()
    {
        return base.Channel.GetMyAlerts();
    }
}
